version: '3.7'
services:
  app:
    image: cristiano23lima/micronaut:11-gradle
    networks:
      - micronaut-network
    ports:
      - 8082:8082
    tty: true
    container_name: cadastro-cliente
    command: bash -c "tail -f /dev/null"
    volumes:
      - ".:/usr/src/app"
networks:
  micronaut-network:
    driver: bridge
    name: micronaut-network
