micronaut:
  application:
    name: cadastroUsuario
datasources:
  default:
    url: jdbc:postgresql://192.168.100.71:5432/usuario-micronaut
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'postgres'
    schema-generate: CREATE
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
kafka.bootstrap.servers: 192.168.100.71:9092
